---
language: ruby
sudo: false
cache: bundler
before_install: "gem update bundler"
script: "bundle exec rake"
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
branches:
  only: master
notifications:
  email: false
